// Danh sách thể loại gợi ý cho ô nhập genre ở admin (datalist autocomplete).
// Khớp gần nhất với primaryGenreName của iTunes + bổ sung V-Pop/K-Pop cho nhạc khu vực.
export const GENRES = [
  'Pop',
  'V-Pop',
  'K-Pop',
  'Hip-Hop/Rap',
  'R&B/Soul',
  'Dance',
  'Electronic',
  'Rock',
  'Alternative',
  'Indie',
  'Ballad',
  'Acoustic',
  'Singer/Songwriter',
  'Country',
  'Latin',
  'Folk',
  'Jazz',
  'Classical',
  'Soundtrack',
  'Lo-Fi',
  'Reggae',
  'Metal',
];
